spring:
  profiles:
    active: local
---

# ?? ?? (?? ????? ??)
spring:
  application:
    name: fm-delivery

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

---

# local ??? ??
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL? Dialect ??

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
    key: ${SECRET_KEY}

---
# prod ??? ??
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${PROD_DB_URL}  # RDS ????? ??
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL? Dialect ??

  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}

jwt:
  secret:
    key: ${PROD_SECRET_KEY}

---
cloud:
  aws:
    s3:
      bucket: fm-delivery-bucket
    credentials:
      access-key: ${PROD_S3_ACCESS_KEY}
      secret-key: ${PROD_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB