spring:
  profiles:
    active: local
---

# ?? ?? (?? ????? ??)
spring:
  application:
    name: fm-delivery

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

---

# local ??? ??
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/fm_server
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL? Dialect ??

  data:
    redis:
      host: localhost
      port: 6379

---
# prod ??? ??
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://db-fm-server.cdsowokk0x7l.ap-northeast-2.rds.amazonaws.com:3306/fm_server  # RDS ????? ??
    username: admin
    password: fm_server
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL? Dialect ??

  data:
    redis:
      host: fm-server-v1.ezwti8.ng.0001.apn2.cache.amazonaws.com
      port: 6379
---
spring:
  data:
    redis:
      host: localhost
      port: 6379

---
cloud:
  aws:
    s3:
      bucket: fm-delivery-bucket
    credentials:
      access-key: AKIAZQ3DSBLVICQ2ZNF4
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB